version: '2'

services:
  nginx:
    build: nginx
    ports:
      - "80:80"
    volumes_from:
      - partkeepr
    depends_on:
      - partkeepr

  partkeepr:
    build: partkeepr
    mem_limit: 512m
    volumes:
      - partkeepr:/var/www/partkeepr
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    environment:
        - MYSQL_ROOT_PASSWORD=foobar
        - MYSQL_DATABASE=partkeepr
        - MYSQL_USER=partkeepr
        - MYSQL_PASSWORD=partkeepr
    volumes:
      - mysqldata:/var/lib/mysql

  cron:
    build: cron
    env_file: .env
    volumes_from:
      - partkeepr
      - mysql

volumes:
  mysqldata:
  partkeepr:
